#constants
STREET = 0
STREET_NUMBER = 1
SUBURBS_MIN_STREET_BOUNDARY = 0
SUBURBS_MAX_STREET_BOUNDARY = 5
SUBURBS_MIN_STREET_NUMBER_BOUNDARY = 0
SUBURBS_MAX_STREET_NUMBER_BOUNDARY = 4

SKYSCRAPERS_MIN_STREET_BOUNDARY = 0
SKYSCRAPERS_MAX_STREET_BOUNDARY = 4
SKYSCRAPERS_MIN_STREET_NUMBER_BOUNDARY = 0
SKYSCRAPERS_MAX_STREET_NUMBER_BOUNDARY = 6

SHAKEDOWN_MIN_STREET_BOUNDARY = 0
SHAKEDOWN_MAX_STREET_BOUNDARY = 6
SHAKEDOWN_MIN_STREET_NUMBER_BOUNDARY = 0
SHAKEDOWN_MAX_STREET_NUMBER_BOUNDARY = 6

MASSIVE_AMOUNT_OF_HOT_PIZZA = 70
MEDIUM_AMOUNT_OF_HOT_PIZZA = 40
SMALL_AMOUNT_OF_HOT_PIZZA = 0

SHOW_ITEM_IN_ROOM = True
HIDE_ITEM_IN_ROOM = False

MAX_AMOUNT_OF_PIZZA_IN_ELEVATOR = 10

#suburbs
MainPizzaKey_ID = 0
SUBURBS_NOTEBOOK_ID = 1
HAIR_DRYER_ID = 2
BACKPACK_ID = 3
BIKE_KEY_ID = 4
WRIST_WATCH_ID = 5
PIZZA_LOCATOR_ID = 6
TRIPPER_GUIDE_ID = 7
COLD_PIZZA_ID = 8
HOT_PIZZA_ID = 9
COIN_ID = 10
GREEN_LAWN_MOWER_KEY_ID = 11
LAWN_MOWER_ID = 12
SHINY_DICE_ID = 13
BIKE_ID = 14
#skyScrapers
GOLDEN_TICKET_ID = 15

MAX_PIZZA_ON_PLAYER = 5
MAX_PIZZA_ON_PLAYER_WITH_BACKPACK = 10
MAX_PIZZA_ON_BIKE = 5
AMOOUNT_OF_ORDERS_IN_SUBURBS = 11

NO_ITEMS_IN_ROOM = -1
NO_VEHICLES_IN_ROOM = -1
NO_PIZZAS_IN_ROOM = -1
OK = 0

BOX_EMPTY = -1

#Errors
NOT_ENOUGH_PIZZA_IN_INVENTORY = -2
NUMBER_OF_PIZZA_MUST_BE_NAMED = -3
TOO_MUCH_PIZZA_ON_ELEVATOR = -4
HOW_MANY_PIZZA = 5
TOO_MUCH_PIZZA_TO_CARRY = 0